modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Fallen-Breath/fabric-mod-template/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/Fallen-Breath/fabric-mod-template"
authors = "niklas2233"
description = '''
Customize the Minecraft window icon with your own custom icons
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${id}.mixins.json"
